node {
    checkout scm
    stage('Build') {
        docker.image('python:2-alpine').inside('-v /root/.m2:/root/.m2') {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        try {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }   
        } 
        catch (exc) {
            echo 'Jenkins: Test stage failed'
            throw exc
        } 
        finally {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                junit 'test-reports/results.xml'
            }
        }
    }
    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
    }
    stage('Deploy') {
        sh '/usr/bin/scp -i idcloudhost.pem sources root@203.145.34.25:/home/hamonangann/sources'
        docker.image('cdrx/pyinstaller-linux:python2').inside('-v /root/.m2:/root/.m2') {
            sh 'ssh -i idcloushost.pem root@203.145.34.25'
            sh 'pyinstaller --onefile sources/add2vals.py'
        }
        archiveArtifacts 'dist/add2vals'
        sleep 60
    }
}
