node {
    def remote = [:]
    remote.name = ''
    remote.host = '203.145.34.25'
    remote.user = 'root'
    remote.password = ${IDCLOUDHOST_PWD}
    remote.allowAnyHosts = true
    checkout scm
    stage('Build') {
        docker.image('python:2-alpine').inside('-v /root/.m2:/root/.m2') {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        try {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }   
        } 
        catch (exc) {
            echo 'Jenkins: Test stage failed'
            throw exc
        } 
        finally {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                junit 'test-reports/results.xml'
            }
        }
    }
    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
    }
    stage('Deploy') {
        sh 'ssh-keyscan -H 203.145.34.25 >> ~/.ssh/known_hosts'
        sh '/usr/bin/scp -i var/jenkins_home/idcloudhost.pem var/jenkins_home/workspace/submission-cicd-pipeline-wibucina/sources root@203.145.34.25:/home/hamonangann/sources'
        sshCommand remote: remote, command: "pyinstaller --onefile sources/add2vals.py"
        archiveArtifacts 'dist/add2vals'
        sleep 60
    }
}
