node {
    checkout scm
    stage('Build') {
        docker.image('python:2-alpine').inside('-v /root/.m2:/root/.m2') {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        try {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }   
        } 
        catch (exc) {
            echo 'Jenkins: Test stage failed'
            throw exc
        } 
        finally {
            docker.image('qnib/pytest').inside('-v /root/.m2:/root/.m2') {
                junit 'test-reports/results.xml'
            }
        }
    }
    stage('Deploy') {
        sleep 60
        echo 'Deploy completed!'
    }
}
